### ISSUE TITLE
State (SA) is missing from the address

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/coorong_district_council_sa_development_applications#1]

**Comment by MichaelBone** [comment]
The addresses are just those from the PDF files on the Coorong web site.  And those addresses don’t actually include the state (eg. see http://www.coorong.sa.gov.au/webdata/resources/minutesAgendas/Approved%20Development%20Applications%20April%202019.pdf).

But it should be easy enough to parse the addresses from the right and insert the “SA” state code if it’s missing.

**Comment by MichaelBone** [comment]
Added the state (where possible) to addresses (in #2).  Also added commas between the street address and suburb information (again, where possible).  And changed to always save the record (as planningalerts now does versioning).
